;;;5. Аббревы
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;my abbrev
(define-abbrev-table 'global-abbrev-table '(
                                            ("f" "function" nil 1)
                                            ("ej" "=>" nil 1)
                                            ("j" "->" nil 1)
                                            ("ar" "array" nil 1)
                                            ("ec" "echo" nil 1)
                                            ("fj" "<?php " nil 1)
                                            ("jf" "?>" nil 1)
                                            ("arr" "array()" nil 1)
                                            ("crt" "CREATE" nil 1)
                                            ("dsc" "DESC" nil 1)
                                            ("ins" "INSERT INTO" nil 2)
                                            ("slct" "SELECT" nil 1)
                                            ("frm" "FROM" nil 1)
                                            ("ltr" "ALTER" nil 1)
                                            ("whr" "WHERE" nil 1)
                                            ("cnt" "COUNT" nil 1)
                                            ("dlt" "DELETE" nil 1)
                                            ("grp" "GROUP" nil 1)
                                            ("jn" "JOIN" nil 1)
                                            ("ebr" "echo '<br>';" nil 2)
                                            ("zz" "<" nil 1)
                                            ("ret" "return" nil 1)
                                            ("fore" "foreach" nil 1)
                                            ("docjs" "document.getElementById" nil 1)
                                            ("archive0" "7z x" nil 2)
                                            ("def" "defun" nil 1)
                                            ("th" "$this->" nil 1)
                                            ("tt" "touch" nil 1)
                                            ("mk" "mkdir" nil 1)
                                            ("ind" "touch index.php" nil 2)
                                            ("pbf" "public function" nil 2)
                                            ("oo" "object" nil 1)
                                            ("cl" "class" nil 1)
                                            ("pub" "public" nil 1)
                                            ("pr" "private" nil 1)
                                            ("pri" "print" nil 1)
                                            ("cnstr" "public function __construct()" nil 3)
                                            ("qq" "<<" nil 1)
                                            ("qqq" "<<<" nil 1)
                                            ("pro" "protected" nil 1)
                                            ("p" "public" nil 1)
                                            ("abs" "abstract" nil 1)
                                            ("ext" "extends" nil 1)
                                            ("q" "<" nil 1)
                                            ("intr" "interface" nil 1)
                                            ("impl" "implements" nil 1)
                                            ("vl" "VALUES" nil 1)
                                            ("upd" "UPDATE" nil 1)
                                            ("vr" "VARCHAR" nil 1)
                                            ("vls" "VALUES" nil 1)
                                            ("vd" "var_dump" nil 1)
                                            ("sys" "systemctl" nil 1)
                                            ("ba" "bash" nil 1)
					    ("ren" "render" nil 1)
					    ("lll" "localhost:8080")
					    ("aa" "action" nil 1)
					    ("ff" "?>" nil 1)
					    ("st" "static")
					    ("pf" "public function" nil 2)
					    ("nm" "namespace" nil 1)
					    ("mgr" "php yii migrate" nil 3)
					    ("mgrc" "php yii migrate/create" nil 3)
					    ("mgrd" "php yii migrate/down" nil 3)
					    ("inh" "{@inheritdoc}" nil 1)
					    ("ord" "ORDER BY" nil 2)
					    ("res" "re-search-forward" nil 1)
					    ("resb" "re-search-backward" nil 1)
					    ("ser" "search-forward" nil 1)
					    ("serb" "search-backward" nil 1)
					    ("reb" "re-building" nil 1)
					    ("replm" "replace-match" nil 1)
					    ("re" "return" nil 1)
					    ("psf" "public static function" nil 3)
					    ("opt" "/opt/php72/bin/php" nil 1)
					    ("ls" "ls -la" nil 2)
                                            ) ) 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
