(deftheme matrix
  "Created 2021-02-01.")

(custom-theme-set-faces
 'matrix
 '(mouse ((t (:background "#7eff00"))))
 '(cursor ((t (:background "#7eff00" :foreground "black"))))
 '(border ((t (:background "orange"))))
 '(bold ((t (:bold t :weight bold))))
 '(bold-italic ((t (:bold t :weight bold))))
 '(button ((t (nil))))
 '(comint-highlight-input ((t (nil))))
 '(comint-highlight-prompt ((t (nil))))
 '(fixed-pitch ((t (nil))))
 '(font-lock-builtin-face ((t (:foreground "pink2"))))
 '(font-lock-comment-face ((t (:italic t :background "black" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "magenta"))))
 '(font-lock-doc-face ((t (nil))))
 '(font-lock-function-name-face ((t (:bold t :underline t :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "yellow1"))))
 '(font-lock-preprocessor-face ((t (nil))))
 '(font-lock-string-face ((t (:foreground "yellow2"))))
 '(font-lock-type-face ((t (:foreground "LightYellow1"))))
 '(font-lock-variable-name-face ((t (:foreground "light green"))))
 '(font-lock-warning-face ((t (nil))))
 '(fringe ((t (nil))))
 '(header-line ((t (nil))))
 '(highlight ((t (:background "#7eff00" :foreground "black"))))
 '(info-header-node ((t (nil))))
 '(info-header-xref ((t (nil))))
 '(info-menu-header ((t (nil))))
 '(info-node ((t (nil))))
 '(info-xref ((t (nil))))
 '(isearch ((t (nil))))
 '(italic ((t (:underline t))))
 '(menu ((t (nil))))
 '(minibuffer-prompt ((t (nil))))
 '(mode-line ((t (:bold t :background "gray" :foreground "black" :weight bold))))
 '(mode-line-inactive ((t (nil))))
 '(mode-line-buffer-id ((t (:background "orange" :foreground "black"))))
 '(region ((t (:background "#7eff00" :foreground "black"))))
 '(scroll-bar ((t (nil))))
 '(secondary-selection ((t (:background "orange" :foreground "black"))))
 '(semantic-unmatched-syntax-face ((t (nil))))
 '(speedbar-button-face ((t (nil))))
 '(speedbar-directory-face ((t (nil))))
 '(speedbar-file-face ((t (nil))))
 '(speedbar-highlight-face ((t (nil))))
 '(speedbar-selected-face ((t (nil))))
 '(speedbar-separator-face ((t (nil))))
 '(speedbar-tag-face ((t (nil))))
 '(term-bold ((t (nil))))
 '(term-underline ((t (nil))))
 '(tool-bar ((t (nil))))
 '(tooltip ((t (nil))))
 '(trailing-whitespace ((t (nil))))
 '(underline ((t (:underline t))))
 '(variable-pitch ((t (nil))))
 '(default ((t (:background "black" :foreground "#7eff00")))))

(provide-theme 'matrix)
